name: prepare-mobile-build
description: Action to prepare environment for mobile build

runs:
  using: composite
  steps:
    - name: Prepare Node Dependencies
      uses: ./.github/actions/prepare-node-deps

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
