name: Exectute Lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Node Dependencies
        uses: ./.github/actions/prepare-node-deps

      - name: Lint
        run: yarn lint
